[project]
name = "mutil-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "chromadb>=1.5.9",
    "langchain>=1.4.3",
    "langchain-chroma>=1.1.0",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.7",
    "langgraph>=1.2.14",
    "pillow>=12.3.0",
    "pypdf>=6.19.0",
    "pypdfium2>=5.14.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.4",
    "rapidocr-onnxruntime>=1.4.4",
    "sentence-transformers>=6.1.0",
]
